### PR TITLE
Uses new version of ml, with updated models

### PR DESCRIPTION
**Pull request by dirkgr**

### CODE REVIEW

**Comment by rodneykinney** [comment]
Can you run a Grobid extraction from this branch? `spark-util/bin/s2-spark-submit --project pipeline --jobDriver pipeline/spark-drivers/grobid-extraction.conf`

**Comment by dirkgr** [comment]
```
Application application_1475435206175_0041 submitted.
Spark Application URI:  http://spark-cluster.s2.dev.ai2:20888/proxy/application_1475435206175_0041/
ResourceManager URI:    http://spark-cluster.s2.dev.ai2:8088/cluster/app/application_1475435206175_0041/
History Server URI: http://spark-cluster.s2.dev.ai2:18080/history/application_1475435206175_0041/1/jobs/
S3 log path:        s3://ai2-s2-spark-cluster/logs/j-QCK7W19GZ7FD/containers/application_1475435206175_0041/
```

**Comment by dirkgr** [comment]
That first test did nothing, because everything was already cached or tombstoned. So I hacked up the caching code to ignore tombstones for paper ids starting with `00`. There are just over 3000 of those. This is that run:

```
Application application_1475435206175_0081 submitted.
Spark Application URI:  http://spark-cluster.s2.dev.ai2:20888/proxy/application_1475435206175_0081/
ResourceManager URI:    http://spark-cluster.s2.dev.ai2:8088/cluster/app/application_1475435206175_0081/
History Server URI: http://spark-cluster.s2.dev.ai2:18080/history/application_1475435206175_0081/1/jobs/
S3 log path:        s3://ai2-s2-spark-cluster/logs/j-QCK7W19GZ7FD/containers/application_1475435206175_0081/
```

**Comment by dirkgr** [comment]
This second run failed completely. First, Grobid could not load the model, and then the server went unresponsive ... it's almost as if my changes didn't take and it just ran the latest master ...

**Comment by dirkgr** [comment]
OK, so on my own cluster, and with more changes to the scholar project and various S3 buckets, this does actually make Grobid work again. @rodneykinney, all good?

**Review by rodneykinney — APPROVED** [review]
All good!

**Pull request merged**
