### PR TITLE
Kermitt rebase

### PR DESCRIPTION
**Pull request by aria42**
This PR just pulls in some commits from the Patrice's repo. I don't know what mechanism we have for checking that this will break stuff in S2. The changes look benign. 

This is in prep for the CRF PR.

### CODE REVIEW

**Comment by cristipp** [comment]
LGTM

**Comment by rodneykinney** [comment]
To validate changes to Grobid, we use the meta-eval repo:
- git clone https://github.com/allenai/meta-eval
- sbt runMain org.allenai.scholar.metrics.metadata.Main runGrobid
- sbt runMain org.allenai.scholar.metrics.metadata.Main evalGrobid

Using meta-eval requires manually setting up a Grobid installation and data
files in a very specific directory structure, as documented in the README.

BTW, for submitting pull requests back to Patrice's Grobid repo, we use the
upstream-master branch, which should differ only in the build setup.

rk

**Comment by aria42** [comment]
So @rodneykinney, assuming that should happen before I merge this PR?

**Comment by aria42** [comment]
Ok, appears meta-eval is the same on the same sample of a few hundred papers:

**Before**:
Metric  Precision   Recall  F1
venueNonEmpty   1   0.09    0.17
venueNormalized 0   0   0
authorLastNameNormalized    0.87    0.24    0.38
year    0.99    0.06    0.11
yearNonEmpty    1   0.06    0.11
authorLastNameNormalizedFirstInitial    0.85    0.24    0.37
authorFullName  0.7 0.19    0.31
titleNonEmpty   1   0.28    0.44
venueExact  0   0   0
titleExact  0.32    0.09    0.14
titleNormalized 0.86    0.24    0.38
bibliography    0.31    0.22    0.26

**After**:
Metric  Precision       Recall  F1
venueNonEmpty   1       0.09    0.17
venueNormalized 0       0       0
authorLastNameNormalized        0.87    0.24    0.38
year    0.99    0.06    0.11
yearNonEmpty    1       0.06    0.11
authorLastNameNormalizedFirstInitial    0.85    0.24    0.37
authorFullName  0.7     0.19    0.31
titleNonEmpty   1       0.28    0.44
venueExact      0       0       0
titleExact      0.32    0.09    0.14
titleNormalized 0.86    0.24    0.38
bibliography    0.31    0.22    0.26

**Comment by aria42** [comment]
Merging soon unless someone has an objection..

**Comment by rodneykinney** [comment]
No objection. After the merge, our metrics will let us know if the change
affected metrics, but it's nice to do this local validation before merging.

rk

**Pull request merged**
